### ISSUE TITLE
Вылет на разговоре с Кругловым

### ISSUE THREAD

**Issue by shuravban** [naxac/CP2_AddOn#4]
Вылет на последнем разговоре с Кругловым на ДТ:

```
[error]Expression    : !phrase_dialog->m_PhraseVector.empty()
[error]Function      : CPhraseDialog::SayPhrase
[error]File          : E:\stalker\sources\trunk\xr_3da\xrGame\PhraseDialog.cpp
[error]Line          : 140
[error]Description   : No available phrase to say, dialog[bar_ecolog_crush_professor_start]
```

Сейвы:

Круглов перед жаркой.sav - https://drive.google.com/file/d/1DwY4jHJasg3AAXYx79aVA4pbgBhG_MvR/view?usp=sharing

Круглов перед последним разговором.sav - https://drive.google.com/file/d/1uvG_LaI3tlqbNdxtPFTtA-x6cmHWnHP0/view?usp=sharing

**Comment by naxac** [comment]
Исправлено: d8e6c9ce4afe3a3bf4a37f15b7972e63a680f316

**Comment by naxac** [comment]
Исправлено: d8e6c9ce4afe3a3bf4a37f15b7972e63a680f316
