### ISSUE TITLE
Сахатый после спасения молчит

### ISSUE THREAD

**Issue by shuravban** [naxac/CP2_AddOn#5]
Сахатый после зачистки церкви молчит. Пробовал разные варианты (с предварительной зачисткой, беготней по болотам в поисках возможных недобитых бандитов, со живыми членами отряда ЧН), но он сразу спавнится "неправильно" - не на коленях.

Сейвы:

Перед первым заходом на болота.sav - https://drive.google.com/file/d/1DJ0e3KSiKdqlJLxU4ZZb_J1MAdQWX4L6/view?usp=sharing

Пленный лазутчик.sav - https://drive.google.com/file/d/1ECLbzvVk1C3WjOLqGrG21OoMI2aXmCk_/view?usp=sharing

Сивый молчит.sav - https://drive.google.com/file/d/1DhMAvsCATk9i06MXodMSi6hZ1F2-PTwU/view?usp=sharing

У последнего сейва неправильное имя, нужно "Сахатый молчит". Не стал исправлять, чтоб не запутаться еще больше))

**Comment by naxac** [comment]
Исправлено: https://github.com/naxac/CP2_AddOn/commit/a3a545eeceedd42c1066e63b422971179ac3f225
